GET http://localhost:3333/health


###

POST http://localhost:3333/api/auth/signup
Content-Type: application/json

{
    "email": "pedrogoettert@hotmail.com", 
    "password": "123456789", 
    "name": "Pedro de Souza Goettert"
}